version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: financeapp_postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: financeapp
        ports:
            - '5432:5432'
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data

    postgres-test:
        image: postgres:latest
        container_name: financeapp_postgres_test
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: financeapp
        ports:
            - '5433:5432' # porta alterada 5433

